name: .NET

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - name: Restore dependencies
        run: dotnet restore
      - name: build
        run: dotnet build  -c Release
      - name: publish
        run: dotnet publish -c Release
      # - name: get_pwd
      #   run: pwd
      - name: Release to S3
        run: bash scripts/pipeline/release.sh ${{secrets.AWS_BUCKET_NAME}} "BuildArtifacts_GithubActions/testBuild.zip" ${{secrets.AWS_ACESS_KEY}} ${{secrets.AWS_ACESS_SECRET}} "app_deploy.zip"
